spring.application.name=animetracker-api

# Configuration H2
spring.datasource.url=jdbc:h2:file:./animetracker
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.try-it-out-enabled=true

# Serveur
server.port=8080

# Désactiver Spring Security temporairement pour le développement
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configuration JWT
jwt.secret=animetrackerSecretKeyForJWTTokenGenerationMustBeLongEnough12345
jwt.expiration=86400000